name: flash_list_view_example
description: Example app demonstrating FlashSliverList in a CustomScrollView.
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flash_list_view:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
